package net.minecraft.init;

import net.minecraft.block.Block;
import net.minecraft.block.BlockBeacon;
import net.minecraft.block.BlockBush;
import net.minecraft.block.BlockCauldron;
import net.minecraft.block.BlockChest;
import net.minecraft.block.BlockDaylightDetector;
import net.minecraft.block.BlockDeadBush;
import net.minecraft.block.BlockDoublePlant;
import net.minecraft.block.BlockFire;
import net.minecraft.block.BlockFlower;
import net.minecraft.block.BlockGrass;
import net.minecraft.block.BlockHopper;
import net.minecraft.block.BlockLeaves;
import net.minecraft.block.BlockLiquid;
import net.minecraft.block.BlockMycelium;
import net.minecraft.block.BlockPistonBase;
import net.minecraft.block.BlockPistonExtension;
import net.minecraft.block.BlockPistonMoving;
import net.minecraft.block.BlockPortal;
import net.minecraft.block.BlockRedstoneComparator;
import net.minecraft.block.BlockRedstoneRepeater;
import net.minecraft.block.BlockRedstoneWire;
import net.minecraft.block.BlockSand;
import net.minecraft.block.BlockSlab;
import net.minecraft.block.BlockStainedGlass;
import net.minecraft.block.BlockStainedGlassPane;
import net.minecraft.block.BlockTallGrass;
import net.minecraft.block.BlockTripWireHook;

public class Blocks {
   public static final Block air;
   public static final Block stone;
   public static final BlockGrass grass;
   public static final Block dirt;
   public static final Block cobblestone;
   public static final Block planks;
   public static final Block sapling;
   public static final Block bedrock;
   public static final BlockLiquid flowing_water;
   public static final Block water;
   public static final BlockLiquid flowing_lava;
   public static final Block lava;
   public static final BlockSand sand;
   public static final Block gravel;
   public static final Block gold_ore;
   public static final Block iron_ore;
   public static final Block coal_ore;
   public static final Block log;
   public static final Block log2;
   public static final BlockLeaves leaves;
   public static final BlockLeaves leaves2;
   public static final Block sponge;
   public static final Block glass;
   public static final Block lapis_ore;
   public static final Block lapis_block;
   public static final Block dispenser;
   public static final Block sandstone;
   public static final Block noteblock;
   public static final Block bed;
   public static final Block golden_rail;
   public static final Block detector_rail;
   public static final BlockPistonBase sticky_piston;
   public static final Block web;
   public static final BlockTallGrass tallgrass;
   public static final BlockDeadBush deadbush;
   public static final BlockPistonBase piston;
   public static final BlockPistonExtension piston_head;
   public static final Block wool;
   public static final BlockPistonMoving piston_extension;
   public static final BlockFlower yellow_flower;
   public static final BlockFlower red_flower;
   public static final BlockBush brown_mushroom;
   public static final BlockBush red_mushroom;
   public static final Block gold_block;
   public static final Block iron_block;
   public static final BlockSlab double_stone_slab;
   public static final BlockSlab stone_slab;
   public static final Block brick_block;
   public static final Block tnt;
   public static final Block bookshelf;
   public static final Block mossy_cobblestone;
   public static final Block obsidian;
   public static final Block torch;
   public static final BlockFire fire;
   public static final Block mob_spawner;
   public static final Block oak_stairs;
   public static final BlockChest chest;
   public static final BlockRedstoneWire redstone_wire;
   public static final Block diamond_ore;
   public static final Block diamond_block;
   public static final Block crafting_table;
   public static final Block wheat;
   public static final Block farmland;
   public static final Block furnace;
   public static final Block lit_furnace;
   public static final Block standing_sign;
   public static final Block wooden_door;
   public static final Block ladder;
   public static final Block rail;
   public static final Block stone_stairs;
   public static final Block wall_sign;
   public static final Block lever;
   public static final Block stone_pressure_plate;
   public static final Block iron_door;
   public static final Block wooden_pressure_plate;
   public static final Block redstone_ore;
   public static final Block lit_redstone_ore;
   public static final Block unlit_redstone_torch;
   public static final Block redstone_torch;
   public static final Block stone_button;
   public static final Block snow_layer;
   public static final Block ice;
   public static final Block snow;
   public static final Block cactus;
   public static final Block clay;
   public static final Block reeds;
   public static final Block jukebox;
   public static final Block fence;
   public static final Block pumpkin;
   public static final Block netherrack;
   public static final Block soul_sand;
   public static final Block glowstone;
   public static final BlockPortal portal;
   public static final Block lit_pumpkin;
   public static final Block cake;
   public static final BlockRedstoneRepeater unpowered_repeater;
   public static final BlockRedstoneRepeater powered_repeater;
   public static final Block trapdoor;
   public static final Block monster_egg;
   public static final Block stonebrick;
   public static final Block brown_mushroom_block;
   public static final Block red_mushroom_block;
   public static final Block iron_bars;
   public static final Block glass_pane;
   public static final Block melon_block;
   public static final Block pumpkin_stem;
   public static final Block melon_stem;
   public static final Block vine;
   public static final Block fence_gate;
   public static final Block brick_stairs;
   public static final Block stone_brick_stairs;
   public static final BlockMycelium mycelium;
   public static final Block waterlily;
   public static final Block nether_brick;
   public static final Block nether_brick_fence;
   public static final Block nether_brick_stairs;
   public static final Block nether_wart;
   public static final Block enchanting_table;
   public static final Block brewing_stand;
   public static final BlockCauldron cauldron;
   public static final Block end_portal;
   public static final Block end_portal_frame;
   public static final Block end_stone;
   public static final Block dragon_egg;
   public static final Block redstone_lamp;
   public static final Block lit_redstone_lamp;
   public static final BlockSlab double_wooden_slab;
   public static final BlockSlab wooden_slab;
   public static final Block cocoa;
   public static final Block sandstone_stairs;
   public static final Block emerald_ore;
   public static final Block ender_chest;
   public static final BlockTripWireHook tripwire_hook;
   public static final Block tripwire;
   public static final Block emerald_block;
   public static final Block spruce_stairs;
   public static final Block birch_stairs;
   public static final Block jungle_stairs;
   public static final Block command_block;
   public static final BlockBeacon beacon;
   public static final Block cobblestone_wall;
   public static final Block flower_pot;
   public static final Block carrots;
   public static final Block potatoes;
   public static final Block wooden_button;
   public static final Block skull;
   public static final Block anvil;
   public static final Block trapped_chest;
   public static final Block light_weighted_pressure_plate;
   public static final Block heavy_weighted_pressure_plate;
   public static final BlockRedstoneComparator unpowered_comparator;
   public static final BlockRedstoneComparator powered_comparator;
   public static final BlockDaylightDetector daylight_detector;
   public static final Block redstone_block;
   public static final Block quartz_ore;
   public static final BlockHopper hopper;
   public static final Block quartz_block;
   public static final Block quartz_stairs;
   public static final Block activator_rail;
   public static final Block dropper;
   public static final Block stained_hardened_clay;
   public static final Block hay_block;
   public static final Block carpet;
   public static final Block hardened_clay;
   public static final Block coal_block;
   public static final Block packed_ice;
   public static final Block acacia_stairs;
   public static final Block dark_oak_stairs;
   public static final BlockDoublePlant double_plant;
   public static final BlockStainedGlass stained_glass;
   public static final BlockStainedGlassPane stained_glass_pane;
   private static final String __OBFID = "CL_00000204";

   static {
      air = (Block)Block.blockRegistry.getObject("air");
      stone = (Block)Block.blockRegistry.getObject("stone");
      grass = (BlockGrass)Block.blockRegistry.getObject("grass");
      dirt = (Block)Block.blockRegistry.getObject("dirt");
      cobblestone = (Block)Block.blockRegistry.getObject("cobblestone");
      planks = (Block)Block.blockRegistry.getObject("planks");
      sapling = (Block)Block.blockRegistry.getObject("sapling");
      bedrock = (Block)Block.blockRegistry.getObject("bedrock");
      flowing_water = (BlockLiquid)Block.blockRegistry.getObject("flowing_water");
      water = (Block)Block.blockRegistry.getObject("water");
      flowing_lava = (BlockLiquid)Block.blockRegistry.getObject("flowing_lava");
      lava = (Block)Block.blockRegistry.getObject("lava");
      sand = (BlockSand)Block.blockRegistry.getObject("sand");
      gravel = (Block)Block.blockRegistry.getObject("gravel");
      gold_ore = (Block)Block.blockRegistry.getObject("gold_ore");
      iron_ore = (Block)Block.blockRegistry.getObject("iron_ore");
      coal_ore = (Block)Block.blockRegistry.getObject("coal_ore");
      log = (Block)Block.blockRegistry.getObject("log");
      log2 = (Block)Block.blockRegistry.getObject("log2");
      leaves = (BlockLeaves)Block.blockRegistry.getObject("leaves");
      leaves2 = (BlockLeaves)Block.blockRegistry.getObject("leaves2");
      sponge = (Block)Block.blockRegistry.getObject("sponge");
      glass = (Block)Block.blockRegistry.getObject("glass");
      lapis_ore = (Block)Block.blockRegistry.getObject("lapis_ore");
      lapis_block = (Block)Block.blockRegistry.getObject("lapis_block");
      dispenser = (Block)Block.blockRegistry.getObject("dispenser");
      sandstone = (Block)Block.blockRegistry.getObject("sandstone");
      noteblock = (Block)Block.blockRegistry.getObject("noteblock");
      bed = (Block)Block.blockRegistry.getObject("bed");
      golden_rail = (Block)Block.blockRegistry.getObject("golden_rail");
      detector_rail = (Block)Block.blockRegistry.getObject("detector_rail");
      sticky_piston = (BlockPistonBase)Block.blockRegistry.getObject("sticky_piston");
      web = (Block)Block.blockRegistry.getObject("web");
      tallgrass = (BlockTallGrass)Block.blockRegistry.getObject("tallgrass");
      deadbush = (BlockDeadBush)Block.blockRegistry.getObject("deadbush");
      piston = (BlockPistonBase)Block.blockRegistry.getObject("piston");
      piston_head = (BlockPistonExtension)Block.blockRegistry.getObject("piston_head");
      wool = (Block)Block.blockRegistry.getObject("wool");
      piston_extension = (BlockPistonMoving)Block.blockRegistry.getObject("piston_extension");
      yellow_flower = (BlockFlower)Block.blockRegistry.getObject("yellow_flower");
      red_flower = (BlockFlower)Block.blockRegistry.getObject("red_flower");
      brown_mushroom = (BlockBush)Block.blockRegistry.getObject("brown_mushroom");
      red_mushroom = (BlockBush)Block.blockRegistry.getObject("red_mushroom");
      gold_block = (Block)Block.blockRegistry.getObject("gold_block");
      iron_block = (Block)Block.blockRegistry.getObject("iron_block");
      double_stone_slab = (BlockSlab)Block.blockRegistry.getObject("double_stone_slab");
      stone_slab = (BlockSlab)Block.blockRegistry.getObject("stone_slab");
      brick_block = (Block)Block.blockRegistry.getObject("brick_block");
      tnt = (Block)Block.blockRegistry.getObject("tnt");
      bookshelf = (Block)Block.blockRegistry.getObject("bookshelf");
      mossy_cobblestone = (Block)Block.blockRegistry.getObject("mossy_cobblestone");
      obsidian = (Block)Block.blockRegistry.getObject("obsidian");
      torch = (Block)Block.blockRegistry.getObject("torch");
      fire = (BlockFire)Block.blockRegistry.getObject("fire");
      mob_spawner = (Block)Block.blockRegistry.getObject("mob_spawner");
      oak_stairs = (Block)Block.blockRegistry.getObject("oak_stairs");
      chest = (BlockChest)Block.blockRegistry.getObject("chest");
      redstone_wire = (BlockRedstoneWire)Block.blockRegistry.getObject("redstone_wire");
      diamond_ore = (Block)Block.blockRegistry.getObject("diamond_ore");
      diamond_block = (Block)Block.blockRegistry.getObject("diamond_block");
      crafting_table = (Block)Block.blockRegistry.getObject("crafting_table");
      wheat = (Block)Block.blockRegistry.getObject("wheat");
      farmland = (Block)Block.blockRegistry.getObject("farmland");
      furnace = (Block)Block.blockRegistry.getObject("furnace");
      lit_furnace = (Block)Block.blockRegistry.getObject("lit_furnace");
      standing_sign = (Block)Block.blockRegistry.getObject("standing_sign");
      wooden_door = (Block)Block.blockRegistry.getObject("wooden_door");
      ladder = (Block)Block.blockRegistry.getObject("ladder");
      rail = (Block)Block.blockRegistry.getObject("rail");
      stone_stairs = (Block)Block.blockRegistry.getObject("stone_stairs");
      wall_sign = (Block)Block.blockRegistry.getObject("wall_sign");
      lever = (Block)Block.blockRegistry.getObject("lever");
      stone_pressure_plate = (Block)Block.blockRegistry.getObject("stone_pressure_plate");
      iron_door = (Block)Block.blockRegistry.getObject("iron_door");
      wooden_pressure_plate = (Block)Block.blockRegistry.getObject("wooden_pressure_plate");
      redstone_ore = (Block)Block.blockRegistry.getObject("redstone_ore");
      lit_redstone_ore = (Block)Block.blockRegistry.getObject("lit_redstone_ore");
      unlit_redstone_torch = (Block)Block.blockRegistry.getObject("unlit_redstone_torch");
      redstone_torch = (Block)Block.blockRegistry.getObject("redstone_torch");
      stone_button = (Block)Block.blockRegistry.getObject("stone_button");
      snow_layer = (Block)Block.blockRegistry.getObject("snow_layer");
      ice = (Block)Block.blockRegistry.getObject("ice");
      snow = (Block)Block.blockRegistry.getObject("snow");
      cactus = (Block)Block.blockRegistry.getObject("cactus");
      clay = (Block)Block.blockRegistry.getObject("clay");
      reeds = (Block)Block.blockRegistry.getObject("reeds");
      jukebox = (Block)Block.blockRegistry.getObject("jukebox");
      fence = (Block)Block.blockRegistry.getObject("fence");
      pumpkin = (Block)Block.blockRegistry.getObject("pumpkin");
      netherrack = (Block)Block.blockRegistry.getObject("netherrack");
      soul_sand = (Block)Block.blockRegistry.getObject("soul_sand");
      glowstone = (Block)Block.blockRegistry.getObject("glowstone");
      portal = (BlockPortal)Block.blockRegistry.getObject("portal");
      lit_pumpkin = (Block)Block.blockRegistry.getObject("lit_pumpkin");
      cake = (Block)Block.blockRegistry.getObject("cake");
      unpowered_repeater = (BlockRedstoneRepeater)Block.blockRegistry.getObject("unpowered_repeater");
      powered_repeater = (BlockRedstoneRepeater)Block.blockRegistry.getObject("powered_repeater");
      trapdoor = (Block)Block.blockRegistry.getObject("trapdoor");
      monster_egg = (Block)Block.blockRegistry.getObject("monster_egg");
      stonebrick = (Block)Block.blockRegistry.getObject("stonebrick");
      brown_mushroom_block = (Block)Block.blockRegistry.getObject("brown_mushroom_block");
      red_mushroom_block = (Block)Block.blockRegistry.getObject("red_mushroom_block");
      iron_bars = (Block)Block.blockRegistry.getObject("iron_bars");
      glass_pane = (Block)Block.blockRegistry.getObject("glass_pane");
      melon_block = (Block)Block.blockRegistry.getObject("melon_block");
      pumpkin_stem = (Block)Block.blockRegistry.getObject("pumpkin_stem");
      melon_stem = (Block)Block.blockRegistry.getObject("melon_stem");
      vine = (Block)Block.blockRegistry.getObject("vine");
      fence_gate = (Block)Block.blockRegistry.getObject("fence_gate");
      brick_stairs = (Block)Block.blockRegistry.getObject("brick_stairs");
      stone_brick_stairs = (Block)Block.blockRegistry.getObject("stone_brick_stairs");
      mycelium = (BlockMycelium)Block.blockRegistry.getObject("mycelium");
      waterlily = (Block)Block.blockRegistry.getObject("waterlily");
      nether_brick = (Block)Block.blockRegistry.getObject("nether_brick");
      nether_brick_fence = (Block)Block.blockRegistry.getObject("nether_brick_fence");
      nether_brick_stairs = (Block)Block.blockRegistry.getObject("nether_brick_stairs");
      nether_wart = (Block)Block.blockRegistry.getObject("nether_wart");
      enchanting_table = (Block)Block.blockRegistry.getObject("enchanting_table");
      brewing_stand = (Block)Block.blockRegistry.getObject("brewing_stand");
      cauldron = (BlockCauldron)Block.blockRegistry.getObject("cauldron");
      end_portal = (Block)Block.blockRegistry.getObject("end_portal");
      end_portal_frame = (Block)Block.blockRegistry.getObject("end_portal_frame");
      end_stone = (Block)Block.blockRegistry.getObject("end_stone");
      dragon_egg = (Block)Block.blockRegistry.getObject("dragon_egg");
      redstone_lamp = (Block)Block.blockRegistry.getObject("redstone_lamp");
      lit_redstone_lamp = (Block)Block.blockRegistry.getObject("lit_redstone_lamp");
      double_wooden_slab = (BlockSlab)Block.blockRegistry.getObject("double_wooden_slab");
      wooden_slab = (BlockSlab)Block.blockRegistry.getObject("wooden_slab");
      cocoa = (Block)Block.blockRegistry.getObject("cocoa");
      sandstone_stairs = (Block)Block.blockRegistry.getObject("sandstone_stairs");
      emerald_ore = (Block)Block.blockRegistry.getObject("emerald_ore");
      ender_chest = (Block)Block.blockRegistry.getObject("ender_chest");
      tripwire_hook = (BlockTripWireHook)Block.blockRegistry.getObject("tripwire_hook");
      tripwire = (Block)Block.blockRegistry.getObject("tripwire");
      emerald_block = (Block)Block.blockRegistry.getObject("emerald_block");
      spruce_stairs = (Block)Block.blockRegistry.getObject("spruce_stairs");
      birch_stairs = (Block)Block.blockRegistry.getObject("birch_stairs");
      jungle_stairs = (Block)Block.blockRegistry.getObject("jungle_stairs");
      command_block = (Block)Block.blockRegistry.getObject("command_block");
      beacon = (BlockBeacon)Block.blockRegistry.getObject("beacon");
      cobblestone_wall = (Block)Block.blockRegistry.getObject("cobblestone_wall");
      flower_pot = (Block)Block.blockRegistry.getObject("flower_pot");
      carrots = (Block)Block.blockRegistry.getObject("carrots");
      potatoes = (Block)Block.blockRegistry.getObject("potatoes");
      wooden_button = (Block)Block.blockRegistry.getObject("wooden_button");
      skull = (Block)Block.blockRegistry.getObject("skull");
      anvil = (Block)Block.blockRegistry.getObject("anvil");
      trapped_chest = (Block)Block.blockRegistry.getObject("trapped_chest");
      light_weighted_pressure_plate = (Block)Block.blockRegistry.getObject("light_weighted_pressure_plate");
      heavy_weighted_pressure_plate = (Block)Block.blockRegistry.getObject("heavy_weighted_pressure_plate");
      unpowered_comparator = (BlockRedstoneComparator)Block.blockRegistry.getObject("unpowered_comparator");
      powered_comparator = (BlockRedstoneComparator)Block.blockRegistry.getObject("powered_comparator");
      daylight_detector = (BlockDaylightDetector)Block.blockRegistry.getObject("daylight_detector");
      redstone_block = (Block)Block.blockRegistry.getObject("redstone_block");
      quartz_ore = (Block)Block.blockRegistry.getObject("quartz_ore");
      hopper = (BlockHopper)Block.blockRegistry.getObject("hopper");
      quartz_block = (Block)Block.blockRegistry.getObject("quartz_block");
      quartz_stairs = (Block)Block.blockRegistry.getObject("quartz_stairs");
      activator_rail = (Block)Block.blockRegistry.getObject("activator_rail");
      dropper = (Block)Block.blockRegistry.getObject("dropper");
      stained_hardened_clay = (Block)Block.blockRegistry.getObject("stained_hardened_clay");
      hay_block = (Block)Block.blockRegistry.getObject("hay_block");
      carpet = (Block)Block.blockRegistry.getObject("carpet");
      hardened_clay = (Block)Block.blockRegistry.getObject("hardened_clay");
      coal_block = (Block)Block.blockRegistry.getObject("coal_block");
      packed_ice = (Block)Block.blockRegistry.getObject("packed_ice");
      acacia_stairs = (Block)Block.blockRegistry.getObject("acacia_stairs");
      dark_oak_stairs = (Block)Block.blockRegistry.getObject("dark_oak_stairs");
      double_plant = (BlockDoublePlant)Block.blockRegistry.getObject("double_plant");
      stained_glass = (BlockStainedGlass)Block.blockRegistry.getObject("stained_glass");
      stained_glass_pane = (BlockStainedGlassPane)Block.blockRegistry.getObject("stained_glass_pane");
   }
}
